# Overview: Cloud Build build pipeline using git tag.
steps:

  - id: build
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |-
      echo date +%s > ./epoch
      docker image build --platform linux/amd64 \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/ws-go-code:$(cat ./version)-$(cat ./epoch)" .
      docker image push --all-tags "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/ws-go-code"

  - id: deploy
    waitFor:
    - build
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
    - -c
    - |-
      gcloud beta workstations configs update ${_CONFIG} \
            --project $PROJECT_ID \
            --region $LOCATION \
            --cluster ${_CLUSTER} \
            --container-custom-image "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/ws-go-code:$(cat ./version)-$(cat ./epoch)"

options:
  # Verify generation of attestations and provenance metadata for this build.
  # Otherwise, GCB generates provenance for global builds only.
  requestedVerifyOption: VERIFIED
